services:
  web:
    image: nginx
    container_name: ressourcesbook_nginx
    restart: always
    ports:
      - "8005:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: ressourcesbook_php
    restart: always
    volumes:
      - .:/var/www/html